// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.5.2.0
//    <NameSpace>com.appdirect.WindowsClient.DataAccess</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><PascalCase>True</PascalCase><BaseClassName>EntityBase</BaseClassName><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><InitializeFields>Collections</InitializeFields><GenerateAllTypes>True</GenerateAllTypes>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace com.appdirect.WindowsClient.DataAccess
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;


    public partial class WebApplicationsList
    {

        private WebApplicationsListApplication[] itemsField;

        [System.Xml.Serialization.XmlElementAttribute("Items")]
        public WebApplicationsListApplication[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    public partial class WebApplicationsListApplication
    {

        private string billingFrequencyField;

        private string blurbField;

        private string buyableField;

        private string descriptionField;

        private string developerNameField;

        private string discountAvailableField;

        private string featuredField;

        private string freeField;

        private string freeTrialOrEditionPresentField;

        private string iconUrlField;

        private string idField;

        private string lastModifiedField;

        private string leadgenField;

        private string nameField;

        private string numRatingsField;

        private string overviewField;

        private string overviewImageUrlField;

        private string popularField;

        private string productTypeField;

        private string publishedOnField;

        private string ratingField;

        private string referableField;

        private string staffPickField;

        private string startingPriceField;

        private string urlField;

        private WebApplicationsListApplicationTagsTag[] tagsField;

        private string hrefField;

        [System.Xml.Serialization.XmlElementAttribute("billingFrequency")]
        public string BillingFrequency
        {
            get
            {
                return this.billingFrequencyField;
            }
            set
            {
                this.billingFrequencyField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("blurb")]
        public string Blurb
        {
            get
            {
                return this.blurbField;
            }
            set
            {
                this.blurbField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("buyable")]
        public string Buyable
        {
            get
            {
                return this.buyableField;
            }
            set
            {
                this.buyableField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("description")]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("developerName")]
        public string DeveloperName
        {
            get
            {
                return this.developerNameField;
            }
            set
            {
                this.developerNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("discountAvailable")]
        public string DiscountAvailable
        {
            get
            {
                return this.discountAvailableField;
            }
            set
            {
                this.discountAvailableField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("featured")]
        public string Featured
        {
            get
            {
                return this.featuredField;
            }
            set
            {
                this.featuredField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("free")]
        public string Free
        {
            get
            {
                return this.freeField;
            }
            set
            {
                this.freeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("freeTrialOrEditionPresent")]
        public string FreeTrialOrEditionPresent
        {
            get
            {
                return this.freeTrialOrEditionPresentField;
            }
            set
            {
                this.freeTrialOrEditionPresentField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("iconUrl")]
        public string IconUrl
        {
            get
            {
                return this.iconUrlField;
            }
            set
            {
                this.iconUrlField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("id")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("lastModified")]
        public string LastModified
        {
            get
            {
                return this.lastModifiedField;
            }
            set
            {
                this.lastModifiedField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("leadgen")]
        public string Leadgen
        {
            get
            {
                return this.leadgenField;
            }
            set
            {
                this.leadgenField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("name")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("numRatings")]
        public string NumRatings
        {
            get
            {
                return this.numRatingsField;
            }
            set
            {
                this.numRatingsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("overview")]
        public string Overview
        {
            get
            {
                return this.overviewField;
            }
            set
            {
                this.overviewField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("overviewImageUrl")]
        public string OverviewImageUrl
        {
            get
            {
                return this.overviewImageUrlField;
            }
            set
            {
                this.overviewImageUrlField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("popular")]
        public string Popular
        {
            get
            {
                return this.popularField;
            }
            set
            {
                this.popularField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("productType")]
        public string ProductType
        {
            get
            {
                return this.productTypeField;
            }
            set
            {
                this.productTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("publishedOn")]
        public string PublishedOn
        {
            get
            {
                return this.publishedOnField;
            }
            set
            {
                this.publishedOnField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("rating")]
        public string Rating
        {
            get
            {
                return this.ratingField;
            }
            set
            {
                this.ratingField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("referable")]
        public string Referable
        {
            get
            {
                return this.referableField;
            }
            set
            {
                this.referableField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("staffPick")]
        public string StaffPick
        {
            get
            {
                return this.staffPickField;
            }
            set
            {
                this.staffPickField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("startingPrice")]
        public string StartingPrice
        {
            get
            {
                return this.startingPriceField;
            }
            set
            {
                this.startingPriceField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("url")]
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tag", typeof(WebApplicationsListApplicationTagsTag), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public WebApplicationsListApplicationTagsTag[] Tags
        {
            get
            {
                return this.tagsField;
            }
            set
            {
                this.tagsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("href")]
        public string Href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }
    }

    public partial class WebApplicationsListApplicationTagsTag
    {

        private string idField;

        private string nameField;

        private string showBadgeField;

        private string typeField;

        [System.Xml.Serialization.XmlElementAttribute("id")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("name")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("showBadge")]
        public string ShowBadge
        {
            get
            {
                return this.showBadgeField;
            }
            set
            {
                this.showBadgeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("type")]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
}
