// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.5.2.0
//    <NameSpace>com.appdirect.WindowsClient</NameSpace><Collection>ObservableCollection</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><PascalCase>False</PascalCase><BaseClassName>EntityBase</BaseClassName><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>ASCII</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><InitializeFields>Collections</InitializeFields><GenerateAllTypes>True</GenerateAllTypes>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace com.appdirect.WindowsClient
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.ObjectModel;


    public partial class applications
    {

        private ObservableCollection<applicationsApplication> itemsField;

        public applications()
        {
            this.itemsField = new ObservableCollection<applicationsApplication>();
        }

        public ObservableCollection<applicationsApplication> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    public partial class applicationsApplication
    {

        private string billingFrequencyField;

        private string blurbField;

        private string buyableField;

        private string descriptionField;

        private string developerNameField;

        private string discountAvailableField;

        private string featuredField;

        private string freeField;

        private string freeTrialOrEditionPresentField;

        private string iconUrlField;

        private string idField;

        private string lastModifiedField;

        private string leadgenField;

        private string nameField;

        private string numRatingsField;

        private string overviewField;

        private string overviewImageUrlField;

        private string popularField;

        private string productTypeField;

        private string publishedOnField;

        private string ratingField;

        private string referableField;

        private string staffPickField;

        private string startingPriceField;

        private string urlField;

        private ObservableCollection<applicationsApplicationTagsTag> tagsField;

        private string hrefField;

        public applicationsApplication()
        {
            this.tagsField = new ObservableCollection<applicationsApplicationTagsTag>();
        }

        public string billingFrequency
        {
            get
            {
                return this.billingFrequencyField;
            }
            set
            {
                this.billingFrequencyField = value;
            }
        }

        public string blurb
        {
            get
            {
                return this.blurbField;
            }
            set
            {
                this.blurbField = value;
            }
        }

        public string buyable
        {
            get
            {
                return this.buyableField;
            }
            set
            {
                this.buyableField = value;
            }
        }

        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        public string developerName
        {
            get
            {
                return this.developerNameField;
            }
            set
            {
                this.developerNameField = value;
            }
        }

        public string discountAvailable
        {
            get
            {
                return this.discountAvailableField;
            }
            set
            {
                this.discountAvailableField = value;
            }
        }

        public string featured
        {
            get
            {
                return this.featuredField;
            }
            set
            {
                this.featuredField = value;
            }
        }

        public string free
        {
            get
            {
                return this.freeField;
            }
            set
            {
                this.freeField = value;
            }
        }

        public string freeTrialOrEditionPresent
        {
            get
            {
                return this.freeTrialOrEditionPresentField;
            }
            set
            {
                this.freeTrialOrEditionPresentField = value;
            }
        }

        public string iconUrl
        {
            get
            {
                return this.iconUrlField;
            }
            set
            {
                this.iconUrlField = value;
            }
        }

        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        public string lastModified
        {
            get
            {
                return this.lastModifiedField;
            }
            set
            {
                this.lastModifiedField = value;
            }
        }

        public string leadgen
        {
            get
            {
                return this.leadgenField;
            }
            set
            {
                this.leadgenField = value;
            }
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string numRatings
        {
            get
            {
                return this.numRatingsField;
            }
            set
            {
                this.numRatingsField = value;
            }
        }

        public string overview
        {
            get
            {
                return this.overviewField;
            }
            set
            {
                this.overviewField = value;
            }
        }

        public string overviewImageUrl
        {
            get
            {
                return this.overviewImageUrlField;
            }
            set
            {
                this.overviewImageUrlField = value;
            }
        }

        public string popular
        {
            get
            {
                return this.popularField;
            }
            set
            {
                this.popularField = value;
            }
        }

        public string productType
        {
            get
            {
                return this.productTypeField;
            }
            set
            {
                this.productTypeField = value;
            }
        }

        public string publishedOn
        {
            get
            {
                return this.publishedOnField;
            }
            set
            {
                this.publishedOnField = value;
            }
        }

        public string rating
        {
            get
            {
                return this.ratingField;
            }
            set
            {
                this.ratingField = value;
            }
        }

        public string referable
        {
            get
            {
                return this.referableField;
            }
            set
            {
                this.referableField = value;
            }
        }

        public string staffPick
        {
            get
            {
                return this.staffPickField;
            }
            set
            {
                this.staffPickField = value;
            }
        }

        public string startingPrice
        {
            get
            {
                return this.startingPriceField;
            }
            set
            {
                this.startingPriceField = value;
            }
        }

        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tag", typeof(applicationsApplicationTagsTag), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ObservableCollection<applicationsApplicationTagsTag> tags
        {
            get
            {
                return this.tagsField;
            }
            set
            {
                this.tagsField = value;
            }
        }

        public string href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }
    }

    public partial class applicationsApplicationTagsTag
    {

        private string idField;

        private string nameField;

        private string showBadgeField;

        private string typeField;

        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string showBadge
        {
            get
            {
                return this.showBadgeField;
            }
            set
            {
                this.showBadgeField = value;
            }
        }

        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
}
