// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.5.2.0
//    <NameSpace>AppDirect.WindowsClient.ObjectMapping</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><PascalCase>True</PascalCase><BaseClassName>EntityBase</BaseClassName><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>ASCII</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><InitializeFields>Collections</InitializeFields><GenerateAllTypes>True</GenerateAllTypes>
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;

namespace AppDirect.WindowsClient
{
    public partial class Myapps
    {
        [XmlElement("Items")]
        public List<MyappsMyapp> Items { get; set; }

        public Myapps()
        {
            this.Items = new List<MyappsMyapp>();
        }
    }

    public partial class MyappsMyapp
    {
        [XmlElement("description")]
        public string Description { get; set; }
        [XmlElement("developerName")]
        public string DeveloperName { get; set; }
        [XmlElement("imageUrl")]
        public string ImageUrl { get; set; }
        [XmlElement("loginUrl")]
        public string LoginUrl { get; set; }
        [XmlElement("marketplaceUrl")]
        public string MarketplaceUrl { get; set; }
        [XmlElement("name")]
        public string Name { get; set; }
        [XmlElement("overview")]
        public string Overview { get; set; }
        [XmlElement("productType")]
        public string ProductType { get; set; }
        [XmlElement("publishedOn")]
        public string PublishedOn { get; set; }
        [XmlElement("status")]
        public string Status { get; set; }
        [XmlElement("startingPrice")]
        public string StartingPrice { get; set; }
        [XmlElement("subscriptionId")]
        public string SubscriptionId { get; set; }
        [XmlElement("subscriptionStatus")]
        public string SubscriptionStatus { get; set; }
        [XmlArray(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItem("entry", typeof(MyappsMyappVersionsEntry), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<MyappsMyappVersionsEntry> Versions { get; set; }


        public MyappsMyapp()
        {
            this.Versions = new List<MyappsMyappVersionsEntry>();
        }
    }

    public partial class MyappsMyappVersionsEntry
    {

        [XmlElement("key")]
        public string Key { get; set; }
        [XmlArray(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItem("value", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<string> Values { get; set; }
    }
}
