// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.5.2.0
//    <NameSpace>AppDirect.WindowsClient.ObjectMapping</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><PascalCase>True</PascalCase><BaseClassName>EntityBase</BaseClassName><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>ASCII</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><InitializeFields>Collections</InitializeFields><GenerateAllTypes>True</GenerateAllTypes>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AppDirect.WindowsClient.ObjectMapping
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class Myapps
    {
        [System.Xml.Serialization.XmlElementAttribute("Items")]
        public List<MyappsMyapp> Items { get; set; }

        public Myapps()
        {
            this.Items = new List<MyappsMyapp>();
        }
    }

    public partial class MyappsMyapp
    {
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public string Description { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("developerName")]
        public string DeveloperName { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("imageUrl")]
        public string ImageUrl { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("loginUrl")]
        public string LoginUrl { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("marketplaceUrl")]
        public string MarketplaceUrl { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("name")]
        public string Name { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("overview")]
        public string Overview { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("productType")]
        public string ProductType { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("publishedOn")]
        public string PublishedOn { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("status")]
        public string Status { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("startingPrice")]
        public string StartingPrice { get; set; }
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", typeof(MyappsMyappVersionsEntry), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<MyappsMyappVersionsEntry> Versions { get; set; }


        public MyappsMyapp()
        {
            this.Versions = new List<MyappsMyappVersionsEntry>();
        }
    }

    public partial class MyappsMyappVersionsEntry
    {

        [System.Xml.Serialization.XmlElementAttribute("key")]
        public string Key { get; set; }
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<string> Values { get; set; }
    }
}
