//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDirect.WindowsClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppDirect.WindowsClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalist Version: .
        /// </summary>
        internal static string AboutString {
            get {
                return ResourceManager.GetString("AboutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appy.exe.
        /// </summary>
        internal static string ApplicationExe {
            get {
                return ResourceManager.GetString("ApplicationExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://test.appdirect.com.
        /// </summary>
        internal static string BaseAppStoreUrl {
            get {
                return ResourceManager.GetString("BaseAppStoreUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking For Updates.
        /// </summary>
        internal static string CheckingForUpdatesString {
            get {
                return ResourceManager.GetString("CheckingForUpdatesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Username or Password.
        /// </summary>
        internal static string CredentialsProblemError {
            get {
                return ResourceManager.GetString("CredentialsProblemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Updates.
        /// </summary>
        internal static string DownloadingUpdatesString {
            get {
                return ResourceManager.GetString("DownloadingUpdatesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.appdirect.com/forgotPassword.
        /// </summary>
        internal static string ForgotPasswordUrlString {
            get {
                return ResourceManager.GetString("ForgotPasswordUrlString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        internal static string GetUpdateString {
            get {
                return ResourceManager.GetString("GetUpdateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://test.appdirect.com/apps/.
        /// </summary>
        internal static string InstallAppTarget {
            get {
                return ResourceManager.GetString("InstallAppTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Updates Now.
        /// </summary>
        internal static string InstallUpdateString {
            get {
                return ResourceManager.GetString("InstallUpdateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use {0}, please log in.
        /// </summary>
        internal static string LoginHeader {
            get {
                return ResourceManager.GetString("LoginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Log In.
        /// </summary>
        internal static string LoginHeaderDefault {
            get {
                return ResourceManager.GetString("LoginHeaderDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error. Please check your internet connection..
        /// </summary>
        internal static string NetworkProblemError {
            get {
                return ResourceManager.GetString("NetworkProblemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Is Up-To-Date.
        /// </summary>
        internal static string NoUpdateFoundString {
            get {
                return ResourceManager.GetString("NoUpdateFoundString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /signupService?email={0}.
        /// </summary>
        internal static string RegisterEmailUrl {
            get {
                return ResourceManager.GetString("RegisterEmailUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact your administrator to uninstall this application.
        /// </summary>
        internal static string UninstallAppDirectApp {
            get {
                return ResourceManager.GetString("UninstallAppDirectApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available!.
        /// </summary>
        internal static string UpdateAvailableString {
            get {
                return ResourceManager.GetString("UpdateAvailableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://windows-client-dev.s3-website-us-east-1.amazonaws.com/updater.exe.
        /// </summary>
        internal static string UpdateFileUrl {
            get {
                return ResourceManager.GetString("UpdateFileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://windows-client-dev.s3-website-us-east-1.amazonaws.com/version.txt.
        /// </summary>
        internal static string VersionFileUrl {
            get {
                return ResourceManager.GetString("VersionFileUrl", resourceCulture);
            }
        }
    }
}
