//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDirect.WindowsClient.Browser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppDirect.WindowsClient.Browser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communications can&apos;t be established, error: {0}.
        /// </summary>
        internal static string Communications_can_t_be_established_error_message {
            get {
                return ResourceManager.GetString("Communications_can_t_be_established_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting data for application id {0}, error: {1}.
        /// </summary>
        internal static string Error_getting_data_error_message {
            get {
                return ResourceManager.GetString("Error_getting_data_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No app data transfered for application with id {0}.
        /// </summary>
        internal static string No_app_data_transfered_error_message {
            get {
                return ResourceManager.GetString("No_app_data_transfered_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No session data transfered for application with id {0}.
        /// </summary>
        internal static string No_session_data_transfered_error_message {
            get {
                return ResourceManager.GetString("No_session_data_transfered_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url for the application with id {0} is empty.
        /// </summary>
        internal static string Url_for_the_application_is_empty_error_message {
            get {
                return ResourceManager.GetString("Url_for_the_application_is_empty_error_message", resourceCulture);
            }
        }
    }
}
